const supportedColor: {
    name: string,
    color: string,
    border: boolean,
}[] = [
    { name: "Black", color: "#000", border: false },
    { name: "White", color: "#fff", border: true },
    { name: "Red", color: "#f00", border: false },
    { name: "Green", color: "#0f0", border: false },
    { name: "Blue", color: "#00f", border: false },
    { name: "Yellow", color: "#ff0", border: true },
    { name: "Cyan", color: "#0ff", border: true },
    { name: "Magenta", color: "#f0f", border: false },
    { name: "Silver", color: "#c0c0c0", border: false },
    { name: "Gray", color: "#808080", border: false },
    { name: "Maroon", color: "#800000", border: false },
    { name: "Olive", color: "#808000", border: false },
    { name: "Green", color: "#008000", border: false },
    { name: "Purple", color: "#800080", border: false },
    { name: "Teal", color: "#008080", border: false },
    { name: "Navy", color: "#000080", border: false },
    { name: "Orange", color: "#ffa500", border: false },
    { name: "Aliceblue", color: "#f0f8ff", border: true },
    { name: "Antiquewhite", color: "#faebd7", border: true },
    { name: "Aquamarine", color: "#7fffd4", border: false },
    { name: "Azure", color: "#f0ffff", border: false },
    { name: "Beige", color: "#f5f5dc", border: true },
    { name: "Bisque", color: "#ffe4c4", border: false },
    { name: "Blanchedalmond", color: "#ffebcd", border: true },
    { name: "Blueviolet", color: "#8a2be2", border: false },
    { name: "Brown", color: "#a52a2a", border: false },
    { name: "Burlywood", color: "#deb887", border: false },
    { name: "Cadetblue", color: "#5f9ea0", border: false },
    { name: "Chartreuse", color: "#7fff00", border: true },
    { name: "Chocolate", color: "#d2691e", border: false },
    { name: "Coral", color: "#ff7f50", border: false },
    { name: "Cornflowerblue", color: "#6495ed", border: false },
];

export default supportedColor;